# Generated by Django 2.2.17 on 2021-03-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('ratings', models.DecimalField(decimal_places=1, max_digits=2)),
                ('release_date', models.DateField()),
                ('duration', models.TimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
